### ISSUE TITLE
Помогите, я что то нажал и все сломалось

### ISSUE THREAD

**Issue by TeqquilaSunset** [panaglev/electronic-deans-office-coursework#1]
Я решил использовать вашу систему для работы нашего деканата, но я что то нажал и все сломалось, теперь у всех студентов сбросились их экзамены, но что самое важное, я не могу скачать пдф файл с расписанием отпусков, помогите. Студенты не важны, главное помогите починить кнопку.

**Comment by pnglv** [comment]
Добрый день, спасибо за Ваш отзыв. Очень странно, что у вас получилось что-то скачать, ведь кнопки не работают 🧐. Смотрю по своей системе, у всех студентов были одни 5-ки. Пдф файл с расписанием отпусков выгрузил, распечатал и направил голубиной почтой. Надеемся на дальнейшее сотрудничество😎.

**Comment by panaglev** [comment]
@TeqquilaSunset 💩

**Comment by TeqquilaSunset** [comment]
👩🏿‍🦲👩🏿‍🦲👩🏿‍🦲👩🏿‍🦲👩🏿‍🦲👩🏿‍🦲
